services:
  dbdental:
    image: mysql:lts
    ports:
      - ${DB_PORT}
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  dentalorders:
    build: ./BackEnd/order_service
    environment:
      SPRING_PORT_ORDER: ${SPRING_PORT_ORDER}
      SPRING_ADDRESS_SERVER: ${SPRING_ADDRESS_SERVER}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PW: ${DB_PW}
      JDBC_DRIVER: ${JDBC_DRIVER}
    restart: always
    networks:
      - internal

  dentalnotifications:
    build: ./BackEnd/notifications_service
    environment:
      SPRING_PORT_NOTIFICATIONS: ${SPRING_PORT_NOTIFICATIONS}
      SPRING_ADDRESS_SERVER: ${SPRING_ADDRESS_SERVER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      EMAIL: ${EMAIL}
      MAIL_PW: ${MAIL_PW}
    restart: always
    networks:
      - internal

  dentalprincipal:
    build: ./BackEnd/principal
    environment:
      SPRING_PORT_SERVER: ${SPRING_PORT_SERVER}
      SPRING_ADDRESS_SERVER: ${SPRING_ADDRESS_SERVER}
      EMAIL_SERVICE: ${EMAIL_SERVICE}
      ORDER_SERVICE: ${ORDER_SERVICE}
      MAIL_PW_2: ${MAIL_PW_2}
      JWT_SECRET: ${JWT_SECRET}
      JWT_COOKIE: ${JWT_COOKIE}
      JWT_TIME: ${JWT_TIME}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PW: ${DB_PW}
      DB_URL_TEST: ${DB_URL_TEST}
      JDBC_DRIVER: ${JDBC_DRIVER}
      DOMAIN_URL: ${DOMAIN_URL}
      DOMAIN: ${DOMAIN}
    restart: always
    depends_on:
      dbdental:
        condition: service_healthy
    networks:
      - internal

  dentalfront:
    build: ./FrontEnd
    ports:
      - ${FRONT_PORT}
    depends_on:
      - dentalprincipal
    networks:
      - internal
      - external

networks:
  internal:
    driver: bridge
  external:
    driver: bridge

volumes:
  mysql_data: